draft-cds-rats-intel-corim-profile.xml: cddl/mask-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/numeric-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/numeric-expr.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/set-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/set-expr.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/tee-advisory-ids-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/tee-attributes-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/tee-cryptokey-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/tee-date-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/tee-digest-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/tee-platform-instance-id-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/tee-isvprodid-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/tee-miscselect-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/tee-model-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/tee-pceid-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/tee-svn-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/tee-tcb-comp-svn-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/tee-tcb-eval-num-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/tee-tcbstatus-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/tee-vendor-type.cddl
draft-cds-rats-intel-corim-profile.xml: cddl/exports/intel-profile.cddl
